### ISSUE TITLE
Android broken on Cordova 8.0.0

### ISSUE THREAD

**Issue by peardox** [sitewaerts/cordova-plugin-document-viewer#91]
`Simons-MBP-2:com.eyelid.pdf.treasure simonbooth$ cordova plugin add cordova-plugin-admobpro
Installing "cordova-plugin-admobpro" for android
Installing "cordova-plugin-extension" for android
Android Studio project detected
Failed to install 'cordova-plugin-admobpro': Error: ENOENT: no such file or directory, open '/Users/simonbooth/dev/cordova/com.eyelid.pdf.treasure/platforms/android/AndroidManifest.xml'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.parseElementtreeSync (/Users/simonbooth/dev/cordova/com.eyelid.pdf.treasure/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
    at new AndroidManifest (/Users/simonbooth/dev/cordova/com.eyelid.pdf.treasure/platforms/android/cordova/lib/AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (/Users/simonbooth/dev/cordova/com.eyelid.pdf.treasure/platforms/android/cordova/lib/AndroidProject.js:99:12)
    at Api.addPlugin (/Users/simonbooth/dev/cordova/com.eyelid.pdf.treasure/platforms/android/cordova/Api.js:223:57)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
(node:22290) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open '/Users/simonbooth/dev/cordova/com.eyelid.pdf.treasure/platforms/android/AndroidManifest.xml'
(node:22290) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by regnete** [comment]
Shouldn't this issue be posted to a cordova-plugin-admobpro  related issue tracker?

**Comment by peardox** [comment]
Oops - sorry - wrong plugin
